# Generated by Django 4.2.6 on 2023-11-07 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='heating',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='heating_notifications', to='rooms.lighting'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='lighting',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='lighting_notifications', to='rooms.lighting'),
        ),
    ]
