# Generated by Django 4.2.6 on 2023-11-07 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_notification_heating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='heating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heating_notifications', to='rooms.lighting'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='lighting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lighting_notifications', to='rooms.lighting'),
        ),
    ]
