# Generated by Django 4.2.6 on 2023-11-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(default='no-slug', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
