# Generated by Django 4.2.6 on 2023-11-15 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_homeappliancedata_time_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='heating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heating_notifications', to='rooms.heating'),
        ),
    ]
