# Generated by Django 4.2.6 on 2023-11-07 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_notification_heating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heating',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='d_heating', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='homeappliance',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d_homeAppliance', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='lighting',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='d_lighting', to='rooms.room'),
        ),
    ]
