# Generated by Django 4.2.6 on 2023-11-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_notification_heating'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightingdata',
            name='open_curtains',
            field=models.BooleanField(default=False),
        ),
    ]
