# Generated by Django 4.2.6 on 2023-11-04 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='rooms.room')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=512)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('devices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='rooms.device')),
            ],
        ),
        migrations.CreateModel(
            name='Lighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brightness_outside', models.FloatField()),
                ('brightness_inside', models.FloatField()),
                ('brightness_desired', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('devices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lightings', to='rooms.device')),
            ],
        ),
        migrations.CreateModel(
            name='HomeAppliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=128)),
                ('power', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('devices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HomeAppliances', to='rooms.device')),
            ],
        ),
        migrations.CreateModel(
            name='Heating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_outside', models.FloatField()),
                ('temperature_inside', models.FloatField()),
                ('temperature_desired', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('devices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heating', to='rooms.device')),
            ],
        ),
    ]
