# Generated by Django 4.2.6 on 2023-11-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_device_notification_lighting_homeappliance_heating'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('light', 'capteur de luminosité'), ('temperature', 'capteur de température'), ('appliance', 'capteur de consommation')], max_length=128),
        ),
    ]
