# Generated by Django 4.2.6 on 2023-12-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_lightingdata_open_curtains'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='night_mode',
            field=models.BooleanField(default=False),
        ),
    ]
