# Generated by Django 4.2.6 on 2023-11-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_device_name_alter_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heating',
            name='temperature_desired',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lighting',
            name='brightness_desired',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
