# Generated by Django 4.2.6 on 2023-12-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heatingprices',
            name='slug',
        ),
        migrations.AlterField(
            model_name='heatingprices',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
